### PR TITLE
Removed duplicated 'curl -X' call in docs

### PR DESCRIPTION
**Pull request by vassilyvv**

### CODE REVIEW

**Review by Benson0224 — APPROVED** [review]
LGTM

**Review by Benson0224 — CHANGES_REQUESTED** [review]
Please keep  " curl -X POST " and remove "curl -X GET "

**Review by Benson0224 — APPROVED** [review]

**Comment by vassilyvv** [comment]
@Benson0224 But POST doesn't work.

**Comment by Benson0224** [comment]
> @Benson0224 But POST doesn't work.

thanks, we will check

**Pull request merged**
