### PR TITLE
doc(release): add signature for GreatVoyage-v4.4.5(Cicero)

### PR DESCRIPTION
**Pull request by Starsakary**

### CODE REVIEW

**Review by ratthakorn2509 — APPROVED** [review]

**Review by Liton23 — APPROVED** [review]

**Review by Liton23 — COMMENTED** [review]
TEWWP5MYVZp2WHGoAJ1o8wJveUNK6MDEoi
0xf7595c31647AA25E0A75f4A11BA30873e65C2e5d
0x473e377559390475212f115338559a0116682868

**Comment by Liton23** [comment]
[docs/releases/index.md](mihaliton478.medium.com) 

0xf7595c31647AA25E0A75f4A11BA30873e65C2e5d
I'm on Instagram as @mihaliton478. Install the app to follow my photos and videos. https://www.instagram.com/invites/contact/?i=1008q75rw3hbz&utm_content=ldauy2l

**Comment by Liton23** [comment]
#124

**Comment by Liton23** [comment]
#123 
0x473e377559390475212f115338559a0116682868

**Comment by Liton23** [comment]
@Cletitia @andelf @ratthakorn2509

**Comment by Liton23** [comment]
GPZbqaLsnXdcLhjBBRTgATzHy0P

**Review by ethan1844 — APPROVED** [review]

**Comment by Liton23** [comment]
#114

**Comment by Liton23** [comment]
@Cletitia @ethan1844 @ratthakorn2509 @Starsakary 

https://youtube.com/channel/UCl20MQ9FKwG0OIIXuy21pPA

**Comment by femge1** [comment]
2022-05-07 9:56 GMT+02:00, LITON MIAH ***@***.***>:

**Pull request merged**
